repos:
-   repo: local
    hooks:
      - id: lint
        name: lint
        entry: make lint
        language: system
        types: [python]
        pass_filenames: false
-   repo: local
    hooks:
      - id: tests
        name: tests
        entry: make test
        language: system
        types: [python]
        pass_filenames: false