version: "3.7"

x-build: &default-build
  context: .
  dockerfile: Docker/dev/Dockerfile

services:
  postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
    ports:
      - 5432:5432
    networks:
      - banco

  lagoa-app:
    build: *default-build
    command: uvicorn Lagoa.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DEBUG=True
    ports:
      - 8000:8000
    networks:
      - back
      - banco

networks:
  banco:
  back:

volumes:
  postgres-db:
