version: "3.7"

x-build: &default-build
  context: .
  dockerfile: Docker/dev/Dockerfile

services:
  lagoa-app:
    build: *default-build
    command: uvicorn Lagoa.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DEBUG=True
    ports:
      - 8000:8000
    networks:
      - back

networks:
  back:
    name: back-lagoa
